name: Publish Package to npmjs
on:
  release:
    types: [published]
jobs:
  test:
    uses: Arlula/nodejs-core-sdk/.github/workflows/test-pr.yml@main
    secrets:
      test_host: ${{ secrets.test_host }}
      test_timeout: ${{ secrets.test_timeout }}
      test_api_key: ${{ secrets.test_api_key }}
      test_api_secret: ${{ secrets.test_api_secret }}
      test_order_key: ${{ secrets.test_order_key }}
      test_order_key2: ${{ secrets.test_order_key2 }}
      test_order_bundle: ${{ secrets.test_order_bundle }}
      test_order_eula: ${{ secrets.test_order_eula }}
      test_order_id: ${{ secrets.test_order_id }}
      test_resource_id: ${{ secrets.test_resource_id }}
      test_resource_file1: ${{ secrets.test_resource_file1 }}
      test_resource_file2: ${{ secrets.test_resource_file2 }}
      test_collection_id: ${{ secrets.test_collection_id }}
      test_item_id1: ${{ secrets.test_item_id1 }}
      test_item_id2: ${{ secrets.test_item_id2 }}
      test_tasking_order_key: ${{ secrets.test_tasking_order_key }}
      test_tasking_order_key2: ${{ secrets.test_tasking_order_key2 }}
      test_tasking_order_eula: ${{ secrets.test_tasking_order_eula }}
      test_tasking_order_bundle: ${{ secrets.test_tasking_order_bundle }}
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i
      - run: npm run build-package
      - run: cd dist && npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}